name: Build and Release

n:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake g++

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my_program
          path: build/my_program

